source 'https://gems.ruby-china.com'

gem 'rake'
gem 'rack'
gem 'rack-cors'
gem 'grape'
gem 'grape-entity'
gem 'activerecord'
gem 'otr-activerecord'
gem 'sqlite3'
gem 'config'
gem 'jwt'
gem 'pundit'
gem 'rest-client'
gem 'aliyun-sdk'
gem 'fastimage' # 获取图片的大小、类型等

group :development, :test do
  gem 'pry-byebug'
  gem 'factory_bot'
end

group :test do
  gem 'minitest'
  gem 'rack-test'
  gem 'database_cleaner'
end
