/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pyblind_test */

#ifndef _Included_com_pyblind_test
#define _Included_com_pyblind_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pyblind_test
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pyblind_test_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
