var L_CANCEL_TEXT = "取消";
var L_INSERT_TEXT = "确定";
var L_LINKIMGBORDER_TEXT = "Display a border around the image link";
var L_LINKSELECT_TEXT = "Select a community page: ";
var L_LINKSELECTPAGE_TEXT = "Select Page";
var L_LINKWEB_TEXT = "输入/修改超连接 ";
var L_PUTITLEBGCOLOR_TEXT = "Set the Background Color";
var L_PUTITLEFONTFACE_TEXT = "设置字体";
var L_PUTITLEFONTSIZE_TEXT = "设置字体大小";
var L_PUTITLEIMAGE_TEXT = "Insert/ Edit Image";
var L_PUTITLELINK_TEXT = "创建/修改超连接";
var L_PUTITLENEWTABLE_TEXT = "创建/修改表格";
var L_PUTITLEPARAGRAPHSTYLE_TEXT = "设置标题大小";
var L_PUTITLETEXTCOLOR_TEXT = "设置字体颜色";
var L_PUTITLEEMOTICON_TEXT = "Insert Emoticon";
var L_STYLEFORMATTED_TEXT = "预定义";
var L_STYLEHEADING_TEXT = "标题 ";
var L_STYLENORMAL_TEXT = "普通";
var L_STYLESAMPLE_TEXT = "AaBbCc012...  ";
var L_TABLEBG_TEXT = "设定背景";
var L_TABLEBORDERS_TEXT = "设定边框";
var L_TABLEINPUTBGCOLOR_TEXT = "背景颜色: ";
var L_TABLEINPUTBGIMGURL_TEXT = "背景图片: ";
var L_TABLEINPUTBORDER_TEXT = "边框宽度: ";
var L_TABLEINPUTBORDERCOLOR_TEXT = "边框颜色: ";
var L_TABLEINPUTCELLPADDING_TEXT = "单元格边框: ";
var L_TABLEINPUTCELLSPACING_TEXT = "单元格间隔: ";
var L_TABLEINPUTCOLUMNS_TEXT = "列: ";
var L_TABLEINPUTROWS_TEXT = "行: ";
var L_TABLEPADDINGANDSPACING_TEXT = "设定边框与间隔值";
var L_TABLEROWSANDCOLS_TEXT = "设定行与列";
var L_TABLEINSERTROW_TEXT = "插入行";
var L_TABLEINSERTCELL_TEXT = "插入列";
var L_TABLEINSERT_TEXT = "创建";
var L_TABLEUPDATE_TEXT = "修改表格";
var L_TABLENEW_TEXT = "新表格";
var L_TABLEEDIT_TEXT = "修改表格";
var L_TIPB_TEXT = "粗体";
var L_TIPBGCOLOR_TEXT = "背景颜色";
var L_TIPCJ_TEXT = "居中";
var L_TIPCOPY_TEXT = "复制";
var L_TIPCUT_TEXT = "剪切";
var L_TIPDINDENT_TEXT = "减少缩进";
var L_TIPFGCOLOR_TEXT = "字体颜色";
var L_TIPFSIZE_TEXT = "字体大小";
var L_TIPFSTYLE_TEXT = "字体";
var L_TIPI_TEXT = "斜体";
var L_TIPIINDENT_TEXT = "增加缩进";
var L_TIPLINE_TEXT = "插入横线";
var L_TIPLINK_TEXT = "插入连接";
var L_TIPLJ_TEXT = "左对齐";
var L_TIPOL_TEXT = "编号";
var L_TIPP_TEXT = "标题大小";
var L_TIPPASTE_TEXT = "粘贴";
var L_TIPPICTURE_TEXT = "Insert Picture";
var L_TIPRJ_TEXT = "右对齐";
var L_TIPTABLE_TEXT = "插入表格";
var L_TIPU_TEXT = "下划线";
var L_TIPUL_TEXT = "项目符号";
var L_TIPEMOTICON_TEXT = "Emoticons";
var L_MODETITLE_TEXT = "HTML 视图";
var L_MODEDESC_TEXT = "  ( 可直接使用HTML编辑 ) ";
var L_CUSTOMFONT_TEXT = "其它字体...";
var L_CUSTOMFONTENTRY_TEXT = "请输入字体名称:";
var L_SAMPLEFONTENTRY_TEXT = "";
var L_CLOSEBUTTON_TEXT = "x";

var L_TBDATABINDING_TEXT = "Columns";
var L_TBDATALABEL_TEXT   = 'Add a placeholder for the selected column.';

var L_TIP_UNDO = "撤消";
var L_TIP_REDO = "恢复";




// List of emoticon gifs. Add or remove to change selection
// arEmoticons - 12x12 pixels
// arBigEmoticons - 16x16 pixels
var L_EMOTICONPATH_TEXT = "image/";
var arEmoticons = new Array("emsmile.gif","emsad.gif","emdgust.gif","emcrook.gif","emsmiled.gif","emsmilep.gif","emsmileo.gif","emwink.gif", "emrose.gif","emlips.gif","emunlove.gif","emlove.gif","emvamp.gif","embeer.gif","emcocktl.gif","emgift.gif","ememail.gif","emthdown.gif","emthup.gif","emphone.gif","emphoto.gif","emmessag.gif","emfemale.gif","emmale.gif");
var arBigEmoticons = new Array("emarrow_right.gif","emarrow_left.gif","emmail_alert.gif","emwww_link.gif","emexclaim.gif","emhammer.gif");

// Customize Font List
// FONTNAME_TEXT - Displayed in the pop-up
// FONTNAMEDEF_TEXT - The font definition used in the HTML
var L_FONTARIAL_TEXT = "Arial";
var L_FONTARIALDEF_TEXT = "Geneva, Arial, Sans-serif";
var L_FONTARIALBLACK_TEXT = "Arial Black";
var L_FONTARIALBLACKDEF_TEXT = "Arial Black, Geneva, Arial, Sans-serif";
var L_FONTCOURIERNEW_TEXT = "Courier New";
var L_FONTCOURIERNEWDEF_TEXT = "Courier New, Courier, Monospace";
var L_FONTTIMESNEWROMAN_TEXT = "Times New Roman";
var L_FONTTIMESNEWROMANDEF_TEXT = "Times New Roman, Times, Serif";
var L_FONTVERDANA_TEXT = "Verdana";
var L_FONTVERDANADEF_TEXT = "Verdana, Geneva, Arial, Sans-serif";
var L_LUCIDAHAND_TEXT = "Lucida Handwriting";
var L_LUCIDAHANDDEF_TEXT = "Lucida Handwriting, Cursive";
var L_GARAMOND_TEXT = "Garamond";
var L_GARAMONDDEF_TEXT = "Garamond, Times, Serif";

var L_FONTST_TEXT		= "宋体"
var L_FONTSTDEF_TEXT	= "宋体"

var L_FONTJT_TEXT		= "楷体"
var L_FONTJTDEF_TEXT	= "楷体_GB2312"

var L_FONTHT_TEXT		= "黑体"
var L_FONTHTDEF_TEXT	= "黑体"

var L_FONTFST_TEXT		= "仿宋体"
var L_FONTFSTDEF_TEXT	= "仿宋_GB2312"

var L_FONTSST_TEXT		= "新宋体"
var L_FONTSSTDEF_TEXT	= "新宋体"


// Add/ Remove fonts by modifying array
// _CFont(Definition, Display Text, Symbol)
// Set Symbol=true for non-alphabetic fonts to append display text in default font to the sample string
function _CFont(szDef,szText,bSymbol) {
	return new Array(szDef,szText,bSymbol);
};

defaultFonts = new Array();

defaultFonts[0] = _CFont(L_FONTSTDEF_TEXT, L_FONTST_TEXT, false);
defaultFonts[1] = _CFont(L_FONTJTDEF_TEXT, L_FONTJT_TEXT, false);
defaultFonts[2] = _CFont(L_FONTHTDEF_TEXT, L_FONTHT_TEXT, false);
defaultFonts[3] = _CFont(L_FONTFSTDEF_TEXT, L_FONTFST_TEXT, false);
defaultFonts[4] = _CFont(L_FONTSSTDEF_TEXT, L_FONTSST_TEXT, false);
defaultFonts[5] = _CFont(L_FONTARIALDEF_TEXT, L_FONTARIAL_TEXT, false);
defaultFonts[6] = _CFont(L_FONTARIALBLACKDEF_TEXT, L_FONTARIALBLACK_TEXT, false);
defaultFonts[7] = _CFont(L_FONTVERDANADEF_TEXT, L_FONTVERDANA_TEXT, false);
defaultFonts[8] = _CFont(L_FONTTIMESNEWROMANDEF_TEXT, L_FONTTIMESNEWROMAN_TEXT, false);
defaultFonts[9] = _CFont(L_GARAMONDDEF_TEXT,L_GARAMOND_TEXT, false);
defaultFonts[10] = _CFont(L_LUCIDAHANDDEF_TEXT,L_LUCIDAHAND_TEXT, false);
defaultFonts[11] = _CFont(L_FONTCOURIERNEWDEF_TEXT, L_FONTCOURIERNEW_TEXT, false);



// Width of each toolbar button
// Entry 5-8 are specify "Paragraph","Font Style", and "Font Size" respectively
// Update widths if localized
var L_TOOLBARGIF_TEXT = "../images/RTE_TB.GIF";
var PHOTO_URL = "../images/photos.htm";
var aSizes = new Array(25,25,25,7,25,25,7,80,76,71,7,25,25,25,8,25,25,25,8,25,25,25,25,8,25,25,25,8);