export default {
  CHANGE_USER_INFO: 'Login/CHANGE_USER_INFO',
  CHANGE_USER_NAME: 'Login/CHANGE_USER_NAME',
  CHANGE_CONTACT_FRIEND_LIST: 'Contacts/CHANGE_CONTACT_FRIEND_LIST',
  CHANGE_NEW_FRIEND_LIST: 'Contacts/CHANGE_NEW_FRIEND_LIST',
  CHANGE_CONTACT_FRIEND_LIST_LOADING: 'Contacts/CHANGE_CONTACT_FRIEND_LIST_LOADING',
  CHANGE_NEW_FRIEND_LIST_LOADING: 'Contacts/CHANGE_NEW_FRIEND_LIST_LOADING',
  CHANGE_CONVERSATION_LIST_LOADING: 'ChatList/CHANGE_CONVERSATION_LIST_LOADING',
  CHANGE_CONVERSATION_LIST: 'ChatList/CHANGE_CONVERSATION_LIST',
  CLEAR_MESSAGE: 'ChatList/CLEAR_MESSAGE',
  CHANGE_MESSAGE_LIST: 'ChatList/CHANGE_MESSAGE_LIST',
};
