/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.center.control;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-19-2007
 * 
 * XDoclet definition:
 * @struts.form name="goodTypeForm"
 */
public class GoodTypeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** typetime property */
	private String typetime;

	/** typename property */
	private String typename;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the typetime.
	 * @return String
	 */
	public String getTypetime() {
		return typetime;
	}

	/** 
	 * Set the typetime.
	 * @param typetime The typetime to set
	 */
	public void setTypetime(String typetime) {
		this.typetime = typetime;
	}

	/** 
	 * Returns the typename.
	 * @return String
	 */
	public String getTypename() {
		return typename;
	}

	/** 
	 * Set the typename.
	 * @param typename The typename to set
	 */
	public void setTypename(String typename) {
		this.typename = typename;
	}
}