package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.net.*;
import msg.*;

public final class client_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
      msg.MsgManager msgManager = null;
      synchronized (_jspx_page_context) {
        msgManager = (msg.MsgManager) _jspx_page_context.getAttribute("msgManager", PageContext.PAGE_SCOPE);
        if (msgManager == null){
          msgManager = new msg.MsgManager();
          _jspx_page_context.setAttribute("msgManager", msgManager, PageContext.PAGE_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      msg.UserManager userManager = null;
      synchronized (_jspx_page_context) {
        userManager = (msg.UserManager) _jspx_page_context.getAttribute("userManager", PageContext.PAGE_SCOPE);
        if (userManager == null){
          userManager = new msg.UserManager();
          _jspx_page_context.setAttribute("userManager", userManager, PageContext.PAGE_SCOPE);
        }
      }
      out.write(' ');
      out.write('\r');
      out.write('\n');

 
	///////////////////////检测Session并获取值/////////////////////////////
	 String username=(String)session.getValue("scomClient");
	 String password=(String)session.getValue("scomPwd");		  
	 if(username==null || username.equals("") ||password==null || password.equals("") ) {			
		out.println("<script language=jscript>alert('你没有登陆或会话已经过期，请重新登陆。');location.assign('index.htm');</script>");			
		return;						
	 }
	 ///////////////////////////////////////////////////////////////////////
 

String vid=request.getParameter("vid");//"3yan1";
String openAgain=request.getParameter("openAgain");
//判断只能由index.htm来调用 
/** 
if(openAgain==null){
	out.println("<html><head></head><body><script language=\"javascript\">parent.open(\"client.jsp?vid="+vid+"&openAgain=true\",\"\", \"Status=no,scrollbars=on\");</script></body></html>");
	return;
}
**/
String curURL=userManager.getUserDomain(vid); 
userManager.putLostVisitorToOffline(curURL,vid);
userManager.markUnreadCommandMessageAsRead(vid);
//if(userManager.getUserState(vid).equals("OFFLINE")){ 
	userManager.changeUserLastTime(vid); //更新最新访问时间					
	//更新访问者当前状态为在线
	userManager.changeUserState(vid,"ONLINE"); // 	 
	String hostInfoInXml=userManager.getHostInfoInXml(vid);	 
	//hostInfoInXml=URLEncoder.encode(hostInfoInXml,"gb2312");
	hostInfoInXml=msg.Escape.escape(hostInfoInXml);
  	msgManager.sendSayMeOnPageInitMsg(vid,"stuff",curURL,hostInfoInXml,"STATECHANGE");
	msgManager.sendSayMeLogonMsg(vid,"stuff",curURL);
	msgManager.tellGroupsImOnlineMsg(vid);//通知群我上线
//out.println(curURL+" "+hostInfoInXml);
//}
//out.println(curURL);
//out.println(curURL+userManager.getSiteUserInXml0(curURL));
msg.Message[] leftMessages=msgManager.readLeftMsg(vid);

String thisdomain="";
String multiDomain="False";
StringTokenizer st = new StringTokenizer(curURL,","); 
if(st.countTokens()>1)
	multiDomain="True";
String firstDomain=null;
while(st.hasMoreTokens()){
	if(firstDomain==null){
		firstDomain= st.nextToken(); 
		thisdomain +=firstDomain+";";
	}else
		thisdomain +=st.nextToken()+";";
}
String myip=request.getRemoteAddr();
String thisname="",siteName="";
int payLevel=-1;
Site site=userManager.getSite2(firstDomain);
thisname=site.getAdminName();
siteName=site.getName();
payLevel=site.getPayLevel();
//String thisname= userManager.getName(vid);
//String siteName=userManager.getSiteName(vid);	

 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>淘客网站监控端</title>\r\n");
      out.write("<!--\r\n");
      out.write("\t\t<meta name=\"content-type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t\t<meta http-equiv='Content-Type' content='text/html; charset=gb2312'>\r\n");
      out.write("-->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/manage.css\" type=\"text/css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/toolbar.css\" type=\"text/css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/talktoolbar.css\" type=\"text/css\">\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction loadJS(){\t\r\n");
      out.write("\t\ttry{\t\r\n");
      out.write("\t\t\tvar url=document.URL;\r\n");
      out.write("\t\t\tvar ni=url.lastIndexOf(\"/\"); \r\n");
      out.write("\t\t\turl=url.substring(0,ni+1);\t\t\t\t \r\n");
      out.write("\t\t\turl=url+\"loadJS.jsp?data=manage\"; \r\n");
      out.write("\t\t\tjsData=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\tjsData.onreadystatechange=function(){ \r\n");
      out.write("\t\t\t\tif(jsData.readyState==4){\r\n");
      out.write("\t\t\t\t\ts=document.createElement(\"script\"); \r\n");
      out.write("\t\t\t\t\ts.text =  jsData.responseText;\r\n");
      out.write("//alert(s.text);\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\tvar head = document.getElementsByTagName('head')[0]; \r\n");
      out.write("\t\t\t\t\thead.appendChild(s);\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t \r\n");
      out.write("\t\t\t\t\treturn;\t\t\t\t \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tjsData.open(\"GET\",url,false); //同步请求\r\n");
      out.write("\t\t\tjsData.send(null);\r\n");
      out.write("\t\t}catch(e){window.alert(e.getMessage);}\r\n");
      out.write("\t}\r\n");
      out.write("//loadJS();\r\n");
      out.write("</script>\r\n");
      out.write("\t\t \r\n");
      out.write(" \t\t<SCRIPT LANGUAGE=\"Javascript\" src=\"scripts/tree.js\"></SCRIPT> \t\t\r\n");
      out.write("\t\t<!--<script language=\"javascript\" src=\"http://webim.100im.cn/loadJS.jsp?data=msg\"></script>-->\t\r\n");
      out.write("<script language=\"javascript\" src=\"scripts/msg.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"scripts/manage.js\"></script>\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"scripts/toolbar.js\"></script>\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"scripts/talktoolbar.js\"></script>\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"scripts/shortcut.js\"></script>\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"scripts/prompt.js\"></script>\t\t\r\n");
      out.write("\t\t<script language=\"javascript\">\r\n");
      out.write("\t\t\tvar thisdomain=\"");
      out.print(thisdomain);
      out.write("\",thisid=\"");
      out.print(vid);
      out.write("\",thisstate=\"ONLINE\",thisname=\"");
      out.print(thisname);
      out.write("\";\r\n");
      out.write("\t\t\tvar curURL=\"");
      out.print(curURL);
      out.write("\";\r\n");
      out.write("\t\t\tvar myip=\"");
      out.print(myip);
      out.write("\";\r\n");
      out.write("\t\t\tvar multiDomain=\"");
      out.print(multiDomain);
      out.write("\";\r\n");
      out.write("\t\t\t//var urlsobj=null;\r\n");
      out.write("\t\t\tvar urlarray=new Array('");
      out.print(siteName);
      out.write("');\r\n");
      out.write("\t\t\tvar disablecount=false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(self.location != top.location)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttop.location = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tfunction GetServerPath()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar url=document.URL;\r\n");
      out.write("\t\t\t\tvar ni=url.lastIndexOf(\"/\"); \r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn url.substring(0,ni+1);\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar currentserver=GetServerPath();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction SwitchURL(selectid)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.detachEvent(\"onunload\",SayMeLogoff);\r\n");
      out.write("\t\t\t\twindow.detachEvent(\"onbeforeunload\",ConfirmOut);\r\n");
      out.write("\t\t\t\tdocument.URL=\"login.aspx?index=\"+selectid;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction doSearch(key)\r\n");
      out.write("\t\t\t{ \r\n");
      out.write("\t\t\t\twindow.open(\"manage/clientManage.jsp?action=search&key=\"+key,\"sw\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction buttonSearch()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar key=document.selection.createRange().text;\r\n");
      out.write("\t\t\t\tif(key==\"\")\r\n");
      out.write("\t\t\t\t\tkey=msg.innerText;\r\n");
      out.write("\t\t\t\tdoSearch(key);\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tfunction checksize()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttry\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tself.moveTo(0,0);\r\n");
      out.write("\t\t\t\t\tself.resizeTo(screen.availWidth,screen.availHeight);\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t//\r\n");
      out.write("\t\t\t\t\tinnermsg.style.left=(document.body.clientWidth-210)+\"px\";\r\n");
      out.write("\t\t\t\t\tinnermsg.style.top=(document.body.clientHeight-140)+\"px\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcatch(e)\r\n");
      out.write("\t\t\t\t{}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    function checkclick()\r\n");
      out.write("\t\t    {\r\n");
      out.write("\t\t        var obj=window.event.srcElement;\r\n");
      out.write("\t\t\t\tif(obj.tagName!=null)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t    if(obj.tagName.toLowerCase()==\"a\")\r\n");
      out.write("\t\t\t\t    {\r\n");
      out.write("\t\t\t\t\t    if(obj.target==\"\"&&obj.href.indexOf(\"#\")==-1)\r\n");
      out.write("\t\t\t\t\t    \tobj.target=\"_blank\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    function setshortcut()\r\n");
      out.write("\t\t    {\r\n");
      out.write("\t\t\t\tif(shortcutdata.readyState==\"complete\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(shortcutdata.documentElement!=null)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\twindow.clearInterval(shortcuttimer);\r\n");
      out.write("\t\t\t\t\t\tCreateBoard(shortcutdata.documentElement,shortcutcontrol.documentElement,\"ShortCutDefine\",175,shortcutboard);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    function reloadShortCut()\r\n");
      out.write("\t\t    {\t\r\n");
      out.write("try{\r\n");
      out.write("\t\t\t\t//url=GetServerPath()+\"manage/functions.aspx?xmlcontent=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22unicode%22%3F%3E%3CQuery%20actionid%3D%223000%22%20mode%3D%2220%22%20resultmode%3D%220%22/%3E\";\r\n");
      out.write("\t\t\t\turl=GetServerPath()+\"getShortcut.jsp?url=\"+curURL;\r\n");
      out.write("//window.alert(url);\r\n");
      out.write("\t\t\t\tshortcutdata=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\tshortcutdata.onreadystatechange=function()\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif(shortcutdata.readyState==4)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tvar shortcutdoc=new ActiveXObject(\"Microsoft.XMLDOM\");\r\n");
      out.write("//window.alert(shortcutdata.responseText);\r\n");
      out.write("\t\t\t\t\t\tshortcutdoc.loadXML(shortcutdata.responseText);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tCreateBoard(shortcutdoc,shortcutcontrol.documentElement,\"ShortCutDefine\",175,shortcutboard);\r\n");
      out.write("\t\t\t\t\t\tvar nRoot=shortcutdoc.selectSingleNode(\"ShortCutDefine\");\r\n");
      out.write("\t\t\t\t\t\tif(nRoot==null)\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\tvar nNew=nRoot.getAttribute(\"unread\");\r\n");
      out.write("\t\t\t\t\t\tif(nNew==null||nNew==\"\"||nNew==\"0\")\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\tunreaddiv.innerText=nNew;\r\n");
      out.write("\t\t\t\t\t\tvoipform.style.display='inline';\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tshortcutdata.open(\"GET\",url,true);\r\n");
      out.write("\t\t\t\tshortcutdata.send(null);\r\n");
      out.write("}catch(e){window.alert(e.getMessage);}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction Setcookie (name, value) {  \r\n");
      out.write("\t\t\t\tvar argc = SetCookie.arguments.length;\r\n");
      out.write("\t\t\t\tvar argv = SetCookie.arguments;    \r\n");
      out.write("\t\t\t\tvar path = (argc > 3) ? argv[3] : null;  \r\n");
      out.write("\t\t\t\tvar domain = (argc > 4) ? argv[4] : null;  \r\n");
      out.write("\t\t\t\tvar secure = (argc > 5) ? argv[5] : false;  \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t\tdocument.cookie = name + \"=\" + value +\r\n");
      out.write("\t\t\t\t((path == null) ? \"\" : (\"; path=\" + path)) +  \r\n");
      out.write("\t\t\t\t((domain == null) ? \"\" : (\"; domain=\" + domain)) +    \r\n");
      out.write("\t\t\t\t((secure == true) ? \"; secure\" : \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction Deletecookie (name) { \r\n");
      out.write("\t\t\tvar exp = new Date();  \r\n");
      out.write("\t\t\texp.setTime (exp.getTime() - 1);  \r\n");
      out.write("\t\t\tvar cval = GetCookie (name);  \r\n");
      out.write("\t\t\tdocument.cookie = name + \"=\" + cval + \"; expires=\" + exp.toGMTString();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getCookieVal (offset) {\r\n");
      out.write("\t\t\tvar endstr = document.cookie.indexOf (\";\", offset);  \r\n");
      out.write("\t\t\tif (endstr == -1)\r\n");
      out.write("\t\t\t\tendstr = document.cookie.length;  \r\n");
      out.write("\t\t\t\treturn unescape(document.cookie.substring(offset, endstr));\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction GetCookie (name) { \r\n");
      out.write("\t\t\t\tvar arg = name + \"=\";  \r\n");
      out.write("\t\t\t\tvar alen = arg.length;  \r\n");
      out.write("\t\t\t\tvar clen = document.cookie.length;  \r\n");
      out.write("\t\t\t\tvar i = 0;  \r\n");
      out.write("\t\t\t\twhile (i < clen) {    \r\n");
      out.write("\t\t\t\tvar j = i + alen;    \r\n");
      out.write("\t\t\t\tif (document.cookie.substring(i, j) == arg)      \r\n");
      out.write("\t\t\t\t\t\treturn getCookieVal (j);    \r\n");
      out.write("\t\t\t\t\t\ti = document.cookie.indexOf(\" \", i) + 1;    \r\n");
      out.write("\t\t\t\t\t\tif (i == 0) break;   \r\n");
      out.write("\t\t\t\t}  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\treturn null;\r\n");
      out.write("\t\t}\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t<xml id=\"xsldata\" src=\"xml/tree.xsl\"></xml>\r\n");
      out.write("\t<xml id=\"vsxsldata\" src=\"xml/mixed.xsl\"></xml>\r\n");
      out.write("\t<xml id=\"shortcutcontrol\" src=\"xml/shortcutcontrol.xml\"></xml>\r\n");
      out.write("<!--\r\n");
      out.write("\t<xml id=\"xmldata\" ><D><GS><G i=\"TALKING\"  t=\"正在交谈\"/><G i=\"stuff\"  t=\"其他客服\"/><U i=\"3yan1\" t=\"1\" s=\"ONLINE\"  ></U><U i=\"3yan2\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan3\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan4\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan5\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan6\" t=\"1\" s=\"OFFLINE\"  ></U><G i=\"ONLINE\"  tag=\"www.3yan.com\" t=\"当前在线\"/><G i=\"ONLINE\"  tag=\"www.netalker.com.cn\" t=\"当前在线\"/></GS><US></US></D></xml>\r\n");
      out.write("\t\r\n");
      out.write("\t<xml id=\"xmldata\" ><D><GS><G i=\"TALKING\"  t=\"正在交谈\"/><G i=\"stuff\"  t=\"其他客服\"/><U i=\"3yan1\" t=\"1\" s=\"ONLINE\"  ></U><U i=\"3yan2\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan3\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan4\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan5\" t=\"1\" s=\"OFFLINE\"  ></U><U i=\"3yan6\" t=\"1\" s=\"OFFLINE\"  ></U><G i=\"ONLINE\"  tag=\"www.3yan.com\" t=\"当前在线\"/><G i=\"ONLINE\"  tag=\"www.netalker.com.cn\" t=\"当前在线\"/></GS><US><U i=\"v10386529\" t=\"0\" s=\"ONLINE\"  v=\"1\"  dm=\"www.netalker.com.cn\" ><I i=\"61.232.3.45\" a=\"北京市-铁通\" o=\"winnt\" bo=\"IE 6.0\" l=\"zh-cn\" p=\"1024*768\" u=\"http://www.netalker.com.cn/\" ad=\"0\"/><VS><T  f=\"\"  ot=\"true\"  u=\"http://www.netalker.com.cn/\"  t=\"09月26日 08:02\"/></VS></U><U i=\"v10386528\" t=\"0\" s=\"ONLINE\"  v=\"1\"  dm=\"www.netalker.com.cn\" ><I i=\"61.232.3.45\" a=\"北京市-铁通\" o=\"winnt\" bo=\"IE 6.0\" l=\"zh-cn\" p=\"1024*768\" u=\"http://www.netalker.com.cn/\" ad=\"0\"/><VS><T  f=\"\"  ot=\"true\"  u=\"http://www.netalker.com.cn/\"  t=\"09月26日 08:02\"/></VS></U></US></D></xml>\r\n");
      out.write("-->\r\n");
      out.write("<xml id=\"xmldata\" >");
      out.print(userManager.getSiteUserInXml0(curURL,vid));
      out.write('\r');
      out.write('\n');
	

//msg.Log.log(userManager.getSiteUserInXml0(curURL,vid));
	String[] ids=userManager.findMyTalkers(vid);
 
	for(int i=0;ids!=null && i<ids.length;i++)
		msgManager.sendMsg(new msg.Message(ids[i],vid,"","ONTALK"));
	msgManager.sendContactMsgToMe(vid);

      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\ta:link\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\ta:visited\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\ta:hover\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor: #0000FF;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\ttext-decoration: underline;\r\n");
      out.write("\t\t}\r\n");
      out.write("\ta:actived\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  onLoad=\"SystemInitial();reloadShortCut();\" oncontextmenu=\"return false;\"  onclick=\"checkclick();\">\r\n");
      out.write("\t<!-- XX层开始  -->\r\n");
      out.write(" \t<div id=\"innermsg\" style=\"border-right:#455690 1px solid;border-top:#a6b4cf 1px solid;z-index:99999;border-left:#a6b4cf 1px solid;border-bottom: #455690 1px solid;background-color:#DBE2F7;position:absolute;height:120px;width:210px;display:none\"></div>\r\n");
      out.write("\t<!-- XX层结束  -->\r\n");
      out.write("\t<!-- 短信提示层开始  -->\r\n");
      out.write("\t<div id=\"voipform\" style=\"z-Index:100;position:absolute;top:200px;left:250px;width:415px;height:140px;");
      out.print((leftMessages!=null&& leftMessages.length>0)?"":"display:none;");
      out.write("border:2px groove;margin:0px;padding:0px;background-image:url('img/talk/bg.gif');\" ondragstart='setCapture();ydxx=event.x-this.offsetLeft;ydyy=event.y-this.offsetTop;' ondrag='this.style.left=event.x-ydxx;this.style.top=event.y-ydyy' ondragend='releaseCapture();'>\r\n");
      out.write("\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"width:95%;color:#FF0000;font-size:12px;filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#C0C0C0', endColorStr='#FFFFFF', gradientType='0');\" valign=\"middle\">\r\n");
      out.write("\t\t<img src=\"img/talk/move.gif\" style=\"margin-top:2px;\"> 系统提示\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#C0C0C0', endColorStr='#FFFFFF', gradientType='0');\">\r\n");
      out.write("\t\t<img src=\"img/talk/cls.gif\" onClick=\"voipform.style.display='none';\" title=\" 关闭\" style=\"cursor:hand;\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" style=\"padding:5px;\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" style=\"font-size:12px;background-image:url('img/talk/bg.gif');\" height=\"93\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t您有&nbsp;<font color=red><span id=\"unreaddiv\"></span></font>");
      out.print((leftMessages!=null&& leftMessages.length>0)?String.valueOf(leftMessages.length):"");
      out.write("条未读信息<BR>点击&nbsp;<font color=green>确认</font>&nbsp;查看信息,点击&nbsp;<font color=green>取消</font>&nbsp;关闭提示窗口\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"100%\" style=\"padding-top:10px;\">\r\n");
      out.write("\t\t\t\t\t<P align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" src=\"img/talk/ok.gif\" onClick=\"voipform.style.display='none';manwin=window.open('manage/clientManage.jsp?action=leaveMsg&vid=");
      out.print(vid);
      out.write("','ydmanage');manwin.focus();\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" src=\"img/talk/canal.gif\" onClick=\"voipform.style.display='none';\" title=\"取消\">\r\n");
      out.write("\t\t\t\t\t</P>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 短信提示层结束  -->\r\n");
      out.write("\t<!-- 发送文件层开始  -->\r\n");
      out.write("\t<div id=\"uploadform\" style=\"z-Index:100;position:absolute;top:200px;left:250px;width:415px;height:140px;display:none;border:2px groove;margin:0px;padding:0px;background-image:url('img/talk/bg.gif');\" ondragstart='setCapture();ydxx=event.x-this.offsetLeft;ydyy=event.y-this.offsetTop;' ondrag='this.style.left=event.x-ydxx;this.style.top=event.y-ydyy' ondragend='releaseCapture();'>\r\n");
      out.write("\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"width:95%;color:#FF0000;font-size:12px;filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#C0C0C0', endColorStr='#FFFFFF', gradientType='0');\" valign=\"middle\">\r\n");
      out.write("\t\t<img src=\"img/talk/move.gif\" style=\"margin-top:2px;\"> 发送文件\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#C0C0C0', endColorStr='#FFFFFF', gradientType='0');\">\r\n");
      out.write("\t\t<img src=\"img/talk/cls.gif\" onClick=\"closeUpload();\" title=\"关闭\" style=\"cursor:hand;margin-top:2px;\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" style=\"padding:5px;\" id=\"uploadtd\">\r\n");
      out.write("\t\t<iframe src=\"\" border=\"0\" name=\"uploadframe\" style=\"width:100%;height:100%\"></iframe>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 发送文件层结束  -->\r\n");
      out.write("\t<!-- 标注浏览者层开始  -->\r\n");
      out.write("\t<div id=\"setnoteform\" style=\"z-Index:100;position:absolute;top:200px;left:250px;width:415px;height:200px;display:none;border:2px groove;margin:0px;padding:0px;filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#FFFFFF', endColorStr='#C0C0C0', gradientType='0');\"  ondragstart='setCapture();ydxx=event.x-this.offsetLeft;ydyy=event.y-this.offsetTop;' ondrag='this.style.left=event.x-ydxx;this.style.top=event.y-ydyy' ondragend='releaseCapture();'>\r\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"font-size:12px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width:95%;color:#FF0000;filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#C0C0C0', endColorStr='#FFFFFF', gradientType='0');\" valign=\"middle\">\r\n");
      out.write("\t\t\t\t<img src=\"img/talk/move.gif\" style=\"margin-top:2px;\"> 用户标注\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\" style=\"filter:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#C0C0C0', endColorStr='#FFFFFF', gradientType='0');\">\r\n");
      out.write("\t\t\t\t<img src=\"img/talk/cls.gif\" onClick=\"setnoteform.style.display='none';\" title=\"关闭\" style=\"cursor:hand;margin-top:2px;\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"labeltd\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<table align=\"left\" cellspacing=\"0\" cellpadding=\"1\" border=\"0\" width=\"100%\" style=\"FONT-SIZE:12px;COLOR:#000066\">\r\n");
      out.write("\t\t\t\t\t\t\t<form name=\"ydv_from\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"65\"><nobr>姓名：</nobr></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"129\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"ydv_vid\" size=\"9\"> <input type=\"text\" id=\"ydv_name\" style=\"WIDTH:105px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"59\">性别：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"ydv_sex\" style=\"WIDTH:50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\" selected>男</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">女</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"65\">电话：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"129\"><input type=\"text\" id=\"ydv_tel\" style=\"WIDTH:105px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"59\">手机：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"ydv_mbl\" style=\"WIDTH:105px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"65\"><nobr>小灵通：</nobr></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"129\"><input type=\"text\" id=\"ydv_smalltel\" style=\"WIDTH:105px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"59\">邮件：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"ydv_email\" style=\"WIDTH:105px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"65\">QQ：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"129\"><input type=\"text\" id=\"ydv_qq\" style=\"WIDTH:105px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"59\">MSN：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"ydv_msn\" style=\"WIDTH:105px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"65\">地址：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"129\"><input type=\"text\" id=\"ydv_add\" style=\"WIDTH:105px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"59\">类别：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><select id=\"ydv_type\"></select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button onClick=\"UpdateLabel()\" style=\"BORDER-RIGHT:#000000 1px solid;BORDER-TOP:#000000 1px solid;FILTER:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#DAF0FD', endColorStr='#7FB7E1', gradientType='0');BORDER-LEFT:#000000 1px solid;WIDTH:60px;COLOR:#000000;BORDER-BOTTOM:#000000 1px solid;HEIGHT:18px;BACKGROUND-COLOR:#ffffff;TEXT-ALIGN:center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"button\">修改标注</button>&nbsp;&nbsp;<button onClick=\"DelLabel()\" style=\"BORDER-RIGHT:#000000 1px solid;BORDER-TOP:#000000 1px solid;FILTER:progid:DXImageTransform.Microsoft.Gradient(startColorStr='#DAF0FD', endColorStr='#7FB7E1', gradientType='0');BORDER-LEFT:#000000 1px solid;WIDTH:60px;COLOR:#000000;BORDER-BOTTOM:#000000 1px solid;HEIGHT:18px;BACKGROUND-COLOR:#ffffff;TEXT-ALIGN:center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"button\">删除标注</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 标注浏览者层结束  -->\r\n");
      out.write("\t<bgsound src=\"\" id=\"soundeffect\" loop=1 autostart=\"false\" />\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"79\">\r\n");
      out.write("\t\t\t\t<!-- 网站信息、客户端状态和菜单行开始 -->\r\n");
      out.write("\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"img/manage/t_4.gif\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"148\" align=\"left\"  id=\"logo1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img  border=0 src='img/manage/t_2.gif' width=\"141\" height=\"78\">\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"bottom\"  id=\"tailpiece1\" width=\"188\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" style=\"font-size:12px\" width=\"188\">\r\n");
      out.write("\t\t\t\t\t\t  <tr><td width=\"180\" nowrap=\"true\" class=\"a_effect\" style=\"cursor:hand;white-space:nowrap;color:#08789D;\">版本: ");
      out.print((payLevel==0)?"标准版":"");
      out.print((payLevel==1)?"专业版":"");
      out.print((payLevel==2)?"商业版":"");
      out.write("</td></tr></table>\r\n");
      out.write("\t\t\t\t\t\t  <table border=\"0\" style=\"font-size:12px\" width=\"188\">\r\n");
      out.write("\t\t\t\t\t\t  <tr><td width=\"180\" nowrap=\"true\" class=\"a_effect\" style=\"cursor:hand;padding-top:2px;padding-bottom:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#08789D;\"  title=\"");
      out.print(siteName);
      out.write('(');
      out.print(thisdomain);
      out.write(")\"><label style=\"cursor:hand\" title=\"点击进入网站:");
      out.print(thisdomain);
      out.write("\" onClick=\"window.open('http://");
      out.print(thisdomain);
      out.write("');return false;\"></label><label id=\"droplabel\"> <!--onClick=\"ShowDropPopup(1);-->");
      out.print(siteName);
      out.write("</label></td></tr></table>\r\n");
      out.write("\t\t\t\t\t\t\t<table style=\"font-size:12px\" width=\"188\">\r\n");
      out.write("\t\t\t\t\t\t  <tr><td width=\"181\"  nowrap=\"true\" class=\"a_effect\" style=\"cursor:hand;padding-top:2px;padding-bottom:2px;overflow:hidden; text-overflow:ellipsis;white-space:nowrap;color:#08789D;\" title=\"点击改变状态\"  onclick=\"showStatus();\"><img width=12 height=12 border=0 id=\"stateimg\"> ");
      out.print(thisname);
      out.write("(<label id=\"statename\"></label>)<font size=\"1\"> >>></font></td></tr></table>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"560\" id=\"maxtoolbar1\" align='center'style=\"padding-left:10px;padding-right:10px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"toolbar1\"  style=\"background-color:#E3F7F9border:3px;width:550px;height:78px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCreateMenu(currentserver+\"xml/toolbar.xml\",\"menu\");\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t<td valign=\"bottom\" id=\"xa\" width='83' >\r\n");
      out.write("\t\t\t\t\t\t\t<!--上右菜单开始-->\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:14px;color:#08789D;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td onClick=\"toolbarAction(60)\" style=\"cursor:hand;\" title=\"点击重新获取本页\">刷新页面</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td height='5'></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td onClick=\"toolbarAction(100)\" style=\"cursor:hand;\" title=\"点击进入系统设置页面\">系统设置</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td height='5'></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td onClick=\"toolbarAction(70)\" style=\"cursor:hand;\" title=\"退出系统\">退出系统</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td height='5'></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!--上右菜单结束-->\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"mintoolbar\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/manage/clarity.gif\" width=\"1\" height=\"1\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<!-- 网站信息、客户端状态和菜单行结束 -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td id=\"line\" height='3'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<!-- main -->\r\n");
      out.write("\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" id=\"mainleft\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 左边用户信息窗口开始 -->\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table border=\"0\" height='24' width='100%' cellpadding=\"0\" cellspacing=\"0\" style=\"width:200px;\" background=\"img/manage/t_12.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"25\" align=\"right\"><img src=\"img/manage/l1.gif\" width=\"16\" height=\"14\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td  align=\"left\" style=\"padding-top:2px;padding-left:5px;\"><b style=\"color:#336699;font-size:12px;\">用户列表</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"menubody\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"sysmenu\" style=\"width:100%;height:100%;font-size:12px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table width='100%' height='100%' border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TABLE BORDER=\"0\" HEIGHT=\"100%\" WIDTH=\"100%\" CELLSPACING=\"0\" CELLPADDING=\"0\" STYLE=\"FONT-SIZE: 13px;color:#08789D;\" ID=\"Table2\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR Height=\"24px\" style=\"background-image: url(img/manage/t_12.gif)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD style=\"width:30px;\" align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"img/manage/l1.gif\" width=\"16\" height=\"14\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD>用户列表</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD colspan=\"3\"><DIV id=\"tree\" STYLE=\"PADDING-TOP: 4px; background-color:#CEEBFA;OVERFLOW-Y:auto;Width=100%;Height=100%\" ></DIV></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr Height=\"410\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TABLE BORDER=\"0\" WIDTH=\"100%\" CELLSPACING=\"0\" CELLPADDING=\"0\" STYLE=\"FONT-SIZE: 13px;color:#08789D;\" HEIGHT=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR HEIGHT=\"24px\" style=\"background-image: url(img/manage/t_12.gif)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD style=\"width:30px;\" align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"img/manage/l2.gif\" width=\"17\" height=\"17\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD colspan='2' valign=\"middle\">用户来源:<B><span id=\"currentuser\"></span></B><img id=\"notesign\" style=\"display:none;cursor:hand\" src=\"img/note.gif\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD  height=\"88\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<DIV id=\"ipdata\" STYLE=\"PADDING-TOP: 4px; background-color:#CEEBFA;OVERFLOW-Y:auto;OVERFLOW-X:none;Width=100%;Height=100%\" ></DIV>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR HEIGHT=\"24px\"  style=\"background-image: url(img/manage/t_12.gif)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD style=\"width:30px;\" align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"img/manage/l3.gif\" width=\"16\" height=\"16\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD colspan='2'>访问轨迹</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD   Height=\"100%\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<DIV id=\"vsdata\" STYLE=\"PADDING-TOP: 4px; background-color:#CEEBFA;OVERFLOW-Y:auto;OVERFLOW-X:none;Width=100%;Height=100%\" ></DIV>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TABLE>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr HEIGHT=\"24px\" style=\"background-image: url(img/manage/t_12.gif)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"3\" id=\"menufoot1\" style=\"font-family:Arial;font-size:12px;padding-left:10px\"><nobr>您的IP:");
      out.print(myip);
      out.write("<nobr/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"3\" height='1' bgcolor='#61C0F6'></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width='1' bgcolor='#61C0F6'></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 左边用户信息窗口结束 -->\r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" id=\"mainmiddle\" style=\"padding:10px;padding-top:0px;padding-bottom:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- main-middle -->\r\n");
      out.write("\t\t\t\t\t\t  <div id=\"middle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 对话显示框开始 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"11\" height=\"25\" align=\"left\" background=\"img/manage/m_15.gif\" id=\"disp11\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"530\" background=\"img/manage/m_22.gif\" id=\"disp21\" style=\"padding-top:2px;\"><font style=\"color:#990000;font-size:12px;\">当前用户：</font><span id=\"dialoger\" style=\"font-size:12px;\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"11\" height=\"25\" align=\"right\" id=\"disp31\"><img src=\"img/manage/m_17.gif\" width=\"11\" height=\"25\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"3\" valign=\"top\" style=\"background:ivory;;border:1px solid #7892C6;border-top: 0px solid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 对话显示frame -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<iframe name=\"historyframe\" style=\"margin-left:0;margin-right:0px;background-color:ivory;\" frameborder=\"0\" width=\"100%\" height=\"100%\" src=\"historylist.htm\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 对话显示框结束 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"height:15px;\"><img src=\"img/manage/clarity.gif\" width=\"1\" height=\"1\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"160\" valign=\"bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框开始 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框上方工具图标开始 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"talk11\" width=\"11\" height=\"25\" background=\"img/manage/m_15.gif\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"talk21\" width=\"530\" background=\"img/manage/m_22.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"talktoolbar\" style=\"width:240px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tCreateToolbar(currentserver+\"xml/talktoolbar.xml\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"talk31\" width=\"11\" height=\"25\"><img src=\"img/manage/m_17.gif\" width=\"11\" height=\"25\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框上方工具图标结束 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"3\" style=\"background:#FFFFFF;border-left:1px solid #7892C6;border-right:1px solid #7892C6;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框输入部分开始 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"ivory\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"msg\" contentEditable style=\"color:#660000;background-color:ivory;font-size:14px;height:88px;width:100%;padding:5px;overflow:auto;border:0px solid;\"  onkeypress=\"SendMsg();\" onKeyDown=\"checkkey();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"width:80px;\" align=\"center\" valign=\"middle\"><img id=\"sender\" src=\"img/talk/send.gif\"  style=\"cursor:hand\" onClick=\"SendMsg();\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td  style=\"width:80px;\" align=\"center\" valign=\"top\"><img id=\"searcher\" src=\"img/talk/search.bmp\" style=\"cursor:hand\" onClick=\"buttonSearch();\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框输入部分结束 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框下方状态行开始 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"talk41\" width=\"11\" height=\"25\" background=\"img/manage/m_21.gif\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"talk51\" width='530' background=\"img/manage/m_22.gif\"><span id=\"talkstatus\" style=\"color:gray;font-size:12px;\"><span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"talk61\" width=\"11\" height=\"25\"><img src=\"img/manage/m_24.gif\" width=\"11\" height=\"25\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框下方状态行结束 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 对话发送框结束 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- main-middle -->\r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" id=\"mainright\" align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- main-right -->\r\n");
      out.write("\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr>\r\n");
      out.write("\t\t\t\t\t\t\t <td width='1' bgcolor=\"#61C0F6\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t <td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:12px;color:#08789D;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR Height=\"24px\" style=\"background-image: url(img/manage/t_12.gif)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD style=\"width:30px;\" align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"img/manage/r1.gif\" style=\"margin-right:3px;cursor:hand\" onClick=\"reloadShortCut();\" title=\"点击更新快捷回复\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>快捷回复</TD>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 快捷回复框开始 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan='2' id=\"rightmiddle1\" valign=\"top\" width='100%' height=\"210\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"shortcutboard\"  style=\"width:190;height:210;OVERFLOW:auto;color:#000000;font-size:12px;padding:5px;background-color:#CEEBFA;\">\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tCreateBoard(currentserver+\"xml/shortcut.xml\",175)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 快捷回复框结束 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--群组开始-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR Height=\"24px\" style=\"background-image: url(img/manage/t_12.gif)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD style=\"width:30px;\" align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"img/manage/r2.gif\" onClick=\"\" style=\"margin-right:3px;cursor:hand\" title=\"点击更新行业群组\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>行业群组</TD>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan='2' id=\"rightmiddle2\" align=\"center\" valign=\"top\"  height='160'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"ff\" style=\"width:100%;height:160px;color:#000000;font-size:12px;padding:5px;background-color:#CEEBFA;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t//CreateBoard(currentserver+\"xml/shortcut.xml\",175)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--群组结束-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--商业资讯开始-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR Height=\"24px\" style=\"background-image: url(img/manage/t_12.gif)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD style=\"width:30px;\" align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"img/manage/r3.gif\" style=\"margin-right:3px;cursor:hand\" onClick=\"\" title=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>淘客推荐</TD>\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan='2' id=\"rightbottom3\" align=\"center\" valign=\"top\"  height='130'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"rightbottomdiv\" style=\"width:100%;height:130px;color:#000000;font-size:12px;padding:5px;background-color:#CEEBFA;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--商业资讯结束-->\r\n");
      out.write(" \t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR Height=\"24px\" style=\"background-image: url(img/manage/t_12.gif)\">\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan='2' style=\"font-size:12px\">&nbsp;&nbsp;<input type=checkbox checked id=\"setalert\" title=\"访客到达时自动提示\">访客提示</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t\t\t </tr></table>\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t<!-- main-right -->\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<!-- main -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td id=\"foot\"><img src=\"img/manage/clarity.gif\" width=\"1\" height=\"1\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
