export default {
  NEW_FRIEND_LIST_CHANGE: 'NEW_FRIEND_LIST_CHANGE',
  USER_NAME_CHANGE: 'USER_NAME_CHANGE',
  CONVERSATION_LIST_LOADING_CHANGE: 'CONVERSATION_LIST_LOADING_CHANGE',
  CONTACT_FRIEND_LIST_LOADING_CHANGE: 'CONTACT_FRIEND_LIST_LOADING_CHANGE',
  MESSAGE_LIST_CHANGE: 'MESSAGE_LIST_CHANGE',
  USER_INFO_CHANGE: 'USER_INFO_CHANGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  CONTACT_FRIEND_LIST_CHANGE: 'CONTACT_FRIEND_LIST_CHANGE',
  CONVERSATION_LIST_CHANGE: 'CONVERSATION_LIST_CHANGE',
};
